name: Build

on:
  schedule:
    - cron: "0 0 * * *" # Everyday at 12am.
  workflow_dispatch:

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./latest/
          file: ./latest/Dockerfile
          tags: |
            nusnus/rust-fat:latest
          no-cache: true
          platforms: |
            linux/amd64
            linux/arm64
          push: true

  build_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./nightly/
          file: ./nightly/Dockerfile
          tags: |
            nusnus/rust-fat:nightly
          no-cache: true
          platforms: |
            linux/amd64
            linux/arm64
          push: true
